FROM maven:3.8.5-openjdk-17
WORKDIR /app
COPY . .
RUN mvn clean install
COPY ./target/springDemoApp-0.0.1-SNAPSHOT.war /app
RUN ls -l
EXPOSE 8000
CMD ["java", "-jar", "springDemoApp-0.0.1-SNAPSHOT.war"]